USE [Travel Agency DB]
GO

INSERT INTO Rooms VALUES (9, 'Room9')
ALTER DATABASE [Travel Agency DB] SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Rooms SET name_room='Room9New1' WHERE id_room=9
WAITFOR DELAY '00:00:05'
COMMIT TRAN

--ALTER DATABASE [Travel Agency DB] SET ALLOW_SNAPSHOT_ISOLATION OFF